spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username : root
    password : Vaishu@99
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

message: developers are coding 